title: LichahaCode AI Posts
description: This blog site is dedicated to sharing AI knowledge!
url: "https://lichahacodes.github.io/AI-posts"

# Just the Docs configuration
theme: just-the-docs
permalink: pretty

# Exclude unnecessary files and folders from the build
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock

# Enable search functionality
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  rel_url: true

# Enable copy button for code blocks
enable_copy_code_button: true

# Set up navigation
nav_enabled: true
nav_sort: case_insensitive

# Plugins used for functionality
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

# Footer configuration
back_to_top: true
last_edit_timestamp: false
gh_edit_link: false

# Optimize HTML output
compress_html:
  clippings: all
  comments: all
  endings: all
